2-Nocaffeine/Backend

src/main/java/com/nocaffeine/ssgclone/brandstore/domain/Brand.java
src/main/java/com/nocaffeine/ssgclone/brandstore/domain/BrandList.java
src/main/java/com/nocaffeine/ssgclone/cart/domain/Cart.java
src/main/java/com/nocaffeine/ssgclone/category/domain/LargeCategory.java
src/main/java/com/nocaffeine/ssgclone/category/domain/MediumCategory.java
src/main/java/com/nocaffeine/ssgclone/category/domain/ProductList.java
src/main/java/com/nocaffeine/ssgclone/category/domain/Small_Category.java
src/main/java/com/nocaffeine/ssgclone/category/domain/TinyCategory.java
src/main/java/com/nocaffeine/ssgclone/image/domain/Image.java
src/main/java/com/nocaffeine/ssgclone/like/domain/BrandLike.java
src/main/java/com/nocaffeine/ssgclone/like/domain/CategoryLike.java
src/main/java/com/nocaffeine/ssgclone/like/domain/ProductLike.java
src/main/java/com/nocaffeine/ssgclone/likefolder/domain/Folder.java
src/main/java/com/nocaffeine/ssgclone/likefolder/domain/FolderList.java
src/main/java/com/nocaffeine/ssgclone/member/domain/Member.java
src/main/java/com/nocaffeine/ssgclone/member/domain/SnsInfo.java
src/main/java/com/nocaffeine/ssgclone/order/domain/OrderProduct.java
src/main/java/com/nocaffeine/ssgclone/order/domain/Orders.java
src/main/java/com/nocaffeine/ssgclone/product/domain/Product.java
src/main/java/com/nocaffeine/ssgclone/product/domain/ProductImage.java
src/main/java/com/nocaffeine/ssgclone/product/domain/Total.java
src/main/java/com/nocaffeine/ssgclone/product/domain/ViewHistory.java
src/main/java/com/nocaffeine/ssgclone/productoption/domain/AddOption.java
src/main/java/com/nocaffeine/ssgclone/productoption/domain/ColorOption.java
src/main/java/com/nocaffeine/ssgclone/productoption/domain/ProductOption.java
src/main/java/com/nocaffeine/ssgclone/productoption/domain/SizeOption.java
src/main/java/com/nocaffeine/ssgclone/qna/domain/Qna.java
src/main/java/com/nocaffeine/ssgclone/review/domain/Review.java
src/main/java/com/nocaffeine/ssgclone/specialprice/domain/SpecialPrice.java
src/main/java/com/nocaffeine/ssgclone/specialprice/domain/SpecialPriceList.java

엔티티 클래스파일 생성

---

src/main/java/com/nocaffeine/ssgclone/member/repository/MemberRepository.java
src/main/java/com/nocaffeine/ssgclone/member/service/MemberService.java
src/main/java/com/nocaffeine/ssgclone/order/controller/OrderController.java
src/main/java/com/nocaffeine/ssgclone/order/domain/Orders.java
src/main/java/com/nocaffeine/ssgclone/order/dto/OrderDto.java
src/main/java/com/nocaffeine/ssgclone/order/repository/OrderProductRepository.java
src/main/java/com/nocaffeine/ssgclone/order/repository/OrderRepository.java
src/main/java/com/nocaffeine/ssgclone/order/service/OrderService.java

order_insert

---

src/main/java/com/nocaffeine/ssgclone/cart/application/CartService.java
src/main/java/com/nocaffeine/ssgclone/cart/application/CartServiceImp.java
src/main/java/com/nocaffeine/ssgclone/cart/domain/Cart.java
src/main/java/com/nocaffeine/ssgclone/cart/infrastructure/CartRepository.java
src/main/java/com/nocaffeine/ssgclone/cart/presentation/CartController.java
src/main/java/com/nocaffeine/ssgclone/product/domain/ProductOption.java
src/main/java/com/nocaffeine/ssgclone/product/infrastructure/ProductOptionRepository.java

feat : 장바구니 추가

---

src/main/java/com/nocaffeine/ssgclone/cart/application/CartService.java
src/main/java/com/nocaffeine/ssgclone/cart/application/CartServiceImp.java
src/main/java/com/nocaffeine/ssgclone/cart/domain/Cart.java
src/main/java/com/nocaffeine/ssgclone/cart/dto/request/CartRemoveListRequest.java
src/main/java/com/nocaffeine/ssgclone/cart/infrastructure/CartRepository.java
src/main/java/com/nocaffeine/ssgclone/cart/presentation/CartController.java
src/main/java/com/nocaffeine/ssgclone/order/domain/Orders.java
src/main/java/com/nocaffeine/ssgclone/product/domain/ProductOption.java
src/main/java/com/nocaffeine/ssgclone/product/infrastructure/ProductOptionRepository.java

<!— Please check the one that applies to this PR using "x". —>

[FEATURE] 장바구니 선택한 상품 삭제

---

src/main/java/com/nocaffeine/ssgclone/common/exception/BaseResponseStatus.java
src/main/java/com/nocaffeine/ssgclone/product/application/ProductOptionService.java
src/main/java/com/nocaffeine/ssgclone/product/application/ProductOptionServiceImpl.java
src/main/java/com/nocaffeine/ssgclone/product/application/ProductService.java
src/main/java/com/nocaffeine/ssgclone/product/application/ProductServiceImpl.java
src/main/java/com/nocaffeine/ssgclone/product/presentation/ProductController.java
src/main/java/com/nocaffeine/ssgclone/product/presentation/ProductOptionController.java

상품 조회 , 상품 옵션 조회, 옵션 선택 완료 상품 조회 도메인 수정

[#28] 상품 조회 , 상품 옵션 조회, 옵션 선택 완료 상품 조회 도메인 수정

---

Dockerfile
Jenkinsfile
src/main/java/com/nocaffeine/ssgclone/cart/application/CartServiceImp.java
src/main/java/com/nocaffeine/ssgclone/cart/dto/request/CartRemoveListRequest.java

feat: jenkinsfiel

---

src/main/java/com/nocaffeine/ssgclone/cart/application/CartService.java
src/main/java/com/nocaffeine/ssgclone/cart/application/CartServiceImp.java
src/main/java/com/nocaffeine/ssgclone/cart/domain/Cart.java
src/main/java/com/nocaffeine/ssgclone/cart/dto/request/CartAddRequest.java
src/main/java/com/nocaffeine/ssgclone/cart/dto/request/CartCountRequest.java
src/main/java/com/nocaffeine/ssgclone/cart/dto/request/CartModifyRequest.java
src/main/java/com/nocaffeine/ssgclone/cart/dto/response/CartCountResponse.java
src/main/java/com/nocaffeine/ssgclone/cart/dto/response/CartListResponse.java
src/main/java/com/nocaffeine/ssgclone/cart/dto/response/CartPriceResponse.java
src/main/java/com/nocaffeine/ssgclone/cart/dto/response/CartTotalPriceResponse.java
src/main/java/com/nocaffeine/ssgclone/cart/infrastructure/CartRepository.java
src/main/java/com/nocaffeine/ssgclone/cart/presentation/CartController.java
src/main/java/com/nocaffeine/ssgclone/common/exception/BaseResponseStatus.java
src/main/java/com/nocaffeine/ssgclone/member/application/MemberService.java
src/main/java/com/nocaffeine/ssgclone/product/infrastructure/AddOptionRepository.java
src/main/java/com/nocaffeine/ssgclone/product/infrastructure/ColorOptionRepository.java
src/main/java/com/nocaffeine/ssgclone/product/infrastructure/SizeOptionRepository.java

문제점 
장바구니 조회시 상품ID만 보낼지, 상품정보 싹 긁어서 보낼지 모르겠음🤮
일단 ID만 보냅니다

[#16] 장바구니 기능 구현

---

Dockerfile
build.gradle
src/main/java/com/nocaffeine/ssgclone/product/application/ProductServiceImpl.java
src/main/java/com/nocaffeine/ssgclone/product/presentation/ProductController.java

chore : 상품 옵션 ë조회 메소드 수정

---

src/main/java/com/nocaffeine/ssgclone/like/application/LikeService.java
src/main/java/com/nocaffeine/ssgclone/like/application/LikeServiceImp.java
src/main/java/com/nocaffeine/ssgclone/like/domain/ProductLike.java
src/main/java/com/nocaffeine/ssgclone/like/dto/request/LikeProductAddRequest.java
src/main/java/com/nocaffeine/ssgclone/like/dto/request/LikeProductRemoveRequest.java
src/main/java/com/nocaffeine/ssgclone/like/dto/request/LikeProductRequest.java
src/main/java/com/nocaffeine/ssgclone/like/infrastructure/ProductLikeRepository.java
src/main/java/com/nocaffeine/ssgclone/like/presentation/LikeController.java

[#34] 좋아요 기능 구현했습니다

---

build.gradle
src/main/java/com/nocaffeine/ssgclone/common/EmailProvider.java
src/main/java/com/nocaffeine/ssgclone/common/exception/BaseResponseStatus.java
src/main/java/com/nocaffeine/ssgclone/member/application/MemberService.java
src/main/java/com/nocaffeine/ssgclone/member/application/MemberServiceImp.java
src/main/java/com/nocaffeine/ssgclone/member/domain/EmailAuth.java
src/main/java/com/nocaffeine/ssgclone/member/dto/request/AuthCheckRequestDto.java
src/main/java/com/nocaffeine/ssgclone/member/dto/request/AuthEmailRequestDto.java
src/main/java/com/nocaffeine/ssgclone/member/infrastructure/EmailAuthRepository.java
src/main/java/com/nocaffeine/ssgclone/member/presentation/MemberController.java
src/main/java/com/nocaffeine/ssgclone/member/vo/request/AuthCheckRequestVo.java
src/main/java/com/nocaffeine/ssgclone/member/vo/request/AuthEmailRequestVo.java
src/main/java/com/nocaffeine/ssgclone/member/vo/request/EmailRequestVo.java

이슈번호 #67 
EmailAuth 엔티티 추가 있습니다.
추가로 yml 설정 필요
문제점 :
인증번호 확인을 해야 데이터가 삭제되는데
인증번호 확인을 하지않으면 데이터가 자꾸 쌓임...

[FEAT] 이메일 인증 

---

src/main/java/com/nocaffeine/ssgclone/common/exception/BaseResponseStatus.java
src/main/java/com/nocaffeine/ssgclone/common/swagger/SwaggerConfig.java
src/main/java/com/nocaffeine/ssgclone/product/application/ProductService.java
src/main/java/com/nocaffeine/ssgclone/product/application/ProductServiceImpl.java
src/main/java/com/nocaffeine/ssgclone/product/application/ViewHistoryService.java
src/main/java/com/nocaffeine/ssgclone/product/application/ViewHistoryServiceImpl.java
src/main/java/com/nocaffeine/ssgclone/product/dto/ViewHistoryListDto.java
src/main/java/com/nocaffeine/ssgclone/product/infrastructure/ProductRepository.java
src/main/java/com/nocaffeine/ssgclone/product/infrastructure/ViewHistoryRepository.java
src/main/java/com/nocaffeine/ssgclone/product/presentation/OptionSelectedProductController.java
src/main/java/com/nocaffeine/ssgclone/product/presentation/ProductController.java
src/main/java/com/nocaffeine/ssgclone/product/presentation/ViewHistoryController.java
src/main/java/com/nocaffeine/ssgclone/product/vo/request/ViewHistoryDeleteRequestVo.java
src/main/java/com/nocaffeine/ssgclone/product/vo/request/ViewHistoryRequestVo.java
src/main/java/com/nocaffeine/ssgclone/product/vo/response/AddOptionResponseVo.java
src/main/java/com/nocaffeine/ssgclone/product/vo/response/ColorOptionResponseVo.java
src/main/java/com/nocaffeine/ssgclone/product/vo/response/OptionSelectedProductResponseVo.java
src/main/java/com/nocaffeine/ssgclone/product/vo/response/ProductResponseVo.java
src/main/java/com/nocaffeine/ssgclone/product/vo/response/ProductSearchResponseVo.java
src/main/java/com/nocaffeine/ssgclone/product/vo/response/SizeOptionResponseVo.java
src/main/java/com/nocaffeine/ssgclone/product/vo/response/ViewHistoryResponseVo.java

상품 검색 조회를 하게 되면 해당 키워드를 포함한 상품의 ID 값을 리스트 형식으로 반환
- 현재는 상품 이름에서 검색 키워드가 포함된 경우만 반환해주지만, 실제론 브랜드명 또는 카테고리에서도 관련이 되어있으면 반환이 되므로 이를 인지하고 추후에 수정할 수 있으면 수정할 것

[FEAT] 상품 검색 조회

---

src/main/java/com/nocaffeine/ssgclone/SsgCloneApplication.java

[REFACTOR] 스웨거 설정 추가

---

src/main/java/com/nocaffeine/ssgclone/SsgCloneApplication.java
src/main/java/com/nocaffeine/ssgclone/common/exception/ExceptionAdvice.java

- 스웨거 로컬주소 추가
- 최상위 Exception 을처리하는 핸들러 추가

[REFACTOR] 스웨거 설정 및 Exception 처리

---

src/main/java/com/nocaffeine/ssgclone/SsgCloneApplication.java
src/main/java/com/nocaffeine/ssgclone/common/exception/BaseResponseStatus.java
src/main/java/com/nocaffeine/ssgclone/member/application/AuthService.java
src/main/java/com/nocaffeine/ssgclone/member/application/AuthServiceImpl.java
src/main/java/com/nocaffeine/ssgclone/member/application/MemberService.java
src/main/java/com/nocaffeine/ssgclone/member/application/MemberServiceImp.java
src/main/java/com/nocaffeine/ssgclone/member/domain/Member.java
src/main/java/com/nocaffeine/ssgclone/member/domain/SnsInfo.java
src/main/java/com/nocaffeine/ssgclone/member/dto/request/SnsMemberAddDto.java
src/main/java/com/nocaffeine/ssgclone/member/dto/request/SnsMemberAddRequestDto.java
src/main/java/com/nocaffeine/ssgclone/member/dto/request/SnsMemberLoginDto.java
src/main/java/com/nocaffeine/ssgclone/member/dto/request/SnsMemberLoginRequestDto.java
src/main/java/com/nocaffeine/ssgclone/member/infrastructure/SnsInfoRepository.java
src/main/java/com/nocaffeine/ssgclone/member/presentation/AuthController.java
src/main/java/com/nocaffeine/ssgclone/member/presentation/MemberController.java
src/main/java/com/nocaffeine/ssgclone/member/vo/request/SnsMemberAddRequestVo.java
src/main/java/com/nocaffeine/ssgclone/member/vo/request/SnsMemberLoginRequestVo.java

이슈번호 #70 
- 소셜 회원가입 및 로그인 구현
- 스웨거 설정 및 코드 리펙토링

[FEAT] 소셜 회원가입 및 로그인 구현

---

src/main/java/com/nocaffeine/ssgclone/member/application/AuthService.java
src/main/java/com/nocaffeine/ssgclone/member/application/AuthServiceImpl.java
src/main/java/com/nocaffeine/ssgclone/member/application/MemberService.java
src/main/java/com/nocaffeine/ssgclone/member/application/MemberServiceImp.java
src/main/java/com/nocaffeine/ssgclone/member/dto/request/SnsMemberLoginRequestDto.java
src/main/java/com/nocaffeine/ssgclone/member/infrastructure/SnsInfoRepository.java
src/main/java/com/nocaffeine/ssgclone/member/presentation/AuthController.java
src/main/java/com/nocaffeine/ssgclone/member/presentation/MemberController.java
src/main/java/com/nocaffeine/ssgclone/member/vo/request/SnsMemberLoginRequestVo.java

- 소셜 로그인 및 회원가입시 소셜타입과 아이디를 비교하는 검증 로직 추가
- 중복된 이메일 검증
- 로그인 회원 관련 컨트롤러 AuthController로 이동

[REFACTOR] : auth 패키지 수정 및 검증로직 추가

---

src/main/java/com/nocaffeine/ssgclone/product/application/ProductImagesServiceImpl.java
src/main/java/com/nocaffeine/ssgclone/product/infrastructure/ProductImageRepository.java
src/main/java/com/nocaffeine/ssgclone/product/presentation/ProductImageController.java
src/main/java/com/nocaffeine/ssgclone/product/vo/response/ProductThumbnailResponseVo.java

[FEAT] : 상품 썸네일 이미지 조회

---

src/main/java/com/nocaffeine/ssgclone/order/domain/OrderProduct.java

refactor: orderproduct change

---

src/main/java/com/nocaffeine/ssgclone/brandstore/infrastructure/BrandListRepository.java
src/main/java/com/nocaffeine/ssgclone/common/exception/BaseResponseStatus.java
src/main/java/com/nocaffeine/ssgclone/common/security/SecurityConfiguration.java
src/main/java/com/nocaffeine/ssgclone/product/domain/Image.java
src/main/java/com/nocaffeine/ssgclone/product/infrastructure/ImageRepository.java
src/main/java/com/nocaffeine/ssgclone/review/application/ReviewService.java
src/main/java/com/nocaffeine/ssgclone/review/application/ReviewServiceImpl.java
src/main/java/com/nocaffeine/ssgclone/review/domain/Review.java
src/main/java/com/nocaffeine/ssgclone/review/domain/ReviewImage.java
src/main/java/com/nocaffeine/ssgclone/review/dto/request/ReviewAddRequestDto.java
src/main/java/com/nocaffeine/ssgclone/review/dto/request/ReviewModifyRequestDto.java
src/main/java/com/nocaffeine/ssgclone/review/dto/request/ReviewRemoveRequestDto.java
src/main/java/com/nocaffeine/ssgclone/review/dto/response/ReviewDetailResponseDto.java
src/main/java/com/nocaffeine/ssgclone/review/dto/response/ReviewImageResponseDto.java
src/main/java/com/nocaffeine/ssgclone/review/dto/response/ReviewListResponseDto.java
src/main/java/com/nocaffeine/ssgclone/review/dto/response/ReviewPossibleWriteResponseDto.java
src/main/java/com/nocaffeine/ssgclone/review/infrastructure/ReviewImageRepository.java
src/main/java/com/nocaffeine/ssgclone/review/infrastructure/ReviewRepository.java
src/main/java/com/nocaffeine/ssgclone/review/presentation/ReviewController.java
src/main/java/com/nocaffeine/ssgclone/review/vo/request/ReviewAddRequestVo.java
src/main/java/com/nocaffeine/ssgclone/review/vo/request/ReviewModifyRequestVo.java
src/main/java/com/nocaffeine/ssgclone/review/vo/request/ReviewRemoveRequestVo.java
src/main/java/com/nocaffeine/ssgclone/review/vo/response/ReviewDetailResponseVo.java
src/main/java/com/nocaffeine/ssgclone/review/vo/response/ReviewImageResponseVo.java
src/main/java/com/nocaffeine/ssgclone/review/vo/response/ReviewListResponseVo.java

[FEAT] 상품 리뷰 구현

---

src/main/java/com/nocaffeine/ssgclone/product/application/ProductService.java
src/main/java/com/nocaffeine/ssgclone/product/application/ProductServiceImpl.java
src/main/java/com/nocaffeine/ssgclone/product/dto/response/ProductCategoryResponseDto.java
src/main/java/com/nocaffeine/ssgclone/product/infrastructure/ProductCategoryListRepository.java
src/main/java/com/nocaffeine/ssgclone/product/presentation/ProductController.java
src/main/java/com/nocaffeine/ssgclone/product/vo/response/OptionSelectedProductListResponseVo.java
src/main/java/com/nocaffeine/ssgclone/product/vo/response/ProductCategoryResponseVo.java

[FEAT] 상품 별 카테고리 조회 #89

---

src/main/java/com/nocaffeine/ssgclone/deliveryaddress/DeliveryAddress.java

[FEAT] 배송지 엔티티 추가

---

src/main/java/com/nocaffeine/ssgclone/category/application/CategoryServiceImp.java
src/main/java/com/nocaffeine/ssgclone/category/domain/LargeCategory.java
src/main/java/com/nocaffeine/ssgclone/category/dto/response/LargeCategoryResponse.java

[REFACTOR] 대카테고리 이미지 추가

---

src/main/java/com/nocaffeine/ssgclone/like/application/BrandLikeService.java
src/main/java/com/nocaffeine/ssgclone/like/application/BrandLikeServiceImp.java
src/main/java/com/nocaffeine/ssgclone/like/application/ProductLikeService.java
src/main/java/com/nocaffeine/ssgclone/like/application/ProductLikeServiceImp.java
src/main/java/com/nocaffeine/ssgclone/like/dto/response/LikeStatusResponseDto.java
src/main/java/com/nocaffeine/ssgclone/like/presentation/BrandLikeController.java
src/main/java/com/nocaffeine/ssgclone/like/presentation/CategoryLikeController.java
src/main/java/com/nocaffeine/ssgclone/like/presentation/ProductLikeController.java
src/main/java/com/nocaffeine/ssgclone/like/vo/response/BrandLikeStatusVo.java
src/main/java/com/nocaffeine/ssgclone/like/vo/response/ProductLikeStatusVo.java

프론트 요청으로 구현
좋아요 여부를 true false로 응답

[FEAT] 좋아요 여부 구현

---

src/main/java/com/nocaffeine/ssgclone/common/exception/BaseResponseStatus.java
src/main/java/com/nocaffeine/ssgclone/deliveryaddress/application/DeliveryAddressService.java
src/main/java/com/nocaffeine/ssgclone/deliveryaddress/application/DeliveryAddressServiceImpl.java
src/main/java/com/nocaffeine/ssgclone/deliveryaddress/domain/DeliveryAddress.java
src/main/java/com/nocaffeine/ssgclone/deliveryaddress/dto/request/DeliveryAddressAddRequestDto.java
src/main/java/com/nocaffeine/ssgclone/deliveryaddress/dto/request/DeliveryAddressModifyRequestDto.java
src/main/java/com/nocaffeine/ssgclone/deliveryaddress/dto/request/DeliveryAddressSetDefaultRequestDto.java
src/main/java/com/nocaffeine/ssgclone/deliveryaddress/dto/response/DeliveryAddressDetailResponseDto.java
src/main/java/com/nocaffeine/ssgclone/deliveryaddress/dto/response/DeliveryAddressListResponseDto.java
src/main/java/com/nocaffeine/ssgclone/deliveryaddress/infrastructure/DeliveryAddressRepository.java
src/main/java/com/nocaffeine/ssgclone/deliveryaddress/presentation/DeliveryAddressController.java
src/main/java/com/nocaffeine/ssgclone/deliveryaddress/vo/request/DeliveryAddressAddRequestVo.java
src/main/java/com/nocaffeine/ssgclone/deliveryaddress/vo/request/DeliveryAddressModifyRequestVo.java
src/main/java/com/nocaffeine/ssgclone/deliveryaddress/vo/request/DeliveryAddressSetDefaultRequestVo.java
src/main/java/com/nocaffeine/ssgclone/deliveryaddress/vo/response/DeliveryAddressDetailResponseVo.java
src/main/java/com/nocaffeine/ssgclone/deliveryaddress/vo/response/DeliveryAddressListResponseVo.java

[FEAT] 배송지 관리 CRUD

---

build.gradle
src/main/java/com/nocaffeine/ssgclone/SsgCloneApplication.java
src/main/java/com/nocaffeine/ssgclone/common/redis/RedisCacheConfig.java
src/main/java/com/nocaffeine/ssgclone/common/redis/RedisConfig.java
src/main/java/com/nocaffeine/ssgclone/common/redis/RedisUtils.java
src/main/java/com/nocaffeine/ssgclone/member/domain/Member.java
src/main/java/com/nocaffeine/ssgclone/specialprice/domain/SpecialPrice.java
src/test/java/com/nocaffeine/ssgclone/RedisUtilsTest.java

feat : redis 추가

---

src/main/java/com/nocaffeine/ssgclone/member/application/AuthServiceImpl.java

refactor : redis 사용 이메일 인증

---

src/main/java/com/nocaffeine/ssgclone/product/presentation/OptionSelectedProductController.java
src/main/java/com/nocaffeine/ssgclone/product/vo/response/OptionSelectedProductListResponseVo.java

refactor : 최종 상품 옵션 조회 수정

---

src/main/java/com/nocaffeine/ssgclone/specialprice/domain/SpecialPrice.java

SpecialPrice entity에 subTitle 컬럼 추가

refactor: specialPrice entity 수정

---

src/main/java/com/nocaffeine/ssgclone/like/application/ProductLikeService.java
src/main/java/com/nocaffeine/ssgclone/like/application/ProductLikeServiceImp.java
src/main/java/com/nocaffeine/ssgclone/like/dto/request/ProductLikeListRequestDto.java
src/main/java/com/nocaffeine/ssgclone/like/presentation/ProductLikeController.java
src/main/java/com/nocaffeine/ssgclone/like/vo/request/ProductLikeListRequestVo.java

[REFACTOR] : 좋아요 여러개 삭제

---

src/main/java/com/nocaffeine/ssgclone/product/application/ProductService.java
src/main/java/com/nocaffeine/ssgclone/product/application/ProductServiceImpl.java
src/main/java/com/nocaffeine/ssgclone/product/application/ViewHistoryService.java
src/main/java/com/nocaffeine/ssgclone/product/application/ViewHistoryServiceImpl.java
src/main/java/com/nocaffeine/ssgclone/product/dto/response/ProductPageListResponseDto.java
src/main/java/com/nocaffeine/ssgclone/product/dto/response/ProductResponseDto.java
src/main/java/com/nocaffeine/ssgclone/product/dto/response/ViewHistoryPageListResponseDto.java
src/main/java/com/nocaffeine/ssgclone/product/infrastructure/ProductRepository.java
src/main/java/com/nocaffeine/ssgclone/product/infrastructure/ViewHistoryRepository.java
src/main/java/com/nocaffeine/ssgclone/product/presentation/ProductController.java
src/main/java/com/nocaffeine/ssgclone/product/presentation/ViewHistoryController.java
src/main/java/com/nocaffeine/ssgclone/product/vo/response/ProductListResponseVo.java
src/main/java/com/nocaffeine/ssgclone/product/vo/response/ProductPageListResponseVo.java
src/main/java/com/nocaffeine/ssgclone/product/vo/response/ViewHistoryPageListResponseVo.java

[REFACTOR] 전체 및 최근 본 상품 리스트 페이지화 #108

---

src/main/java/com/nocaffeine/ssgclone/brandstore/application/BrandService.java
src/main/java/com/nocaffeine/ssgclone/brandstore/application/BrandServiceImp.java
src/main/java/com/nocaffeine/ssgclone/brandstore/dto/response/BrandProductIdPageListResponseDto.java
src/main/java/com/nocaffeine/ssgclone/brandstore/dto/response/BrandProductIdResponseDto.java
src/main/java/com/nocaffeine/ssgclone/brandstore/infrastructure/BrandListRepository.java
src/main/java/com/nocaffeine/ssgclone/brandstore/presentation/BrandController.java
src/main/java/com/nocaffeine/ssgclone/brandstore/vo/response/BrandProductIdPageListResponseVo.java
src/main/java/com/nocaffeine/ssgclone/product/application/ProductService.java
src/main/java/com/nocaffeine/ssgclone/product/application/ProductServiceImpl.java
src/main/java/com/nocaffeine/ssgclone/product/dto/response/product/ProductPageListResponseDto.java
src/main/java/com/nocaffeine/ssgclone/product/infrastructure/ProductRepository.java
src/main/java/com/nocaffeine/ssgclone/product/presentation/ProductController.java
src/main/java/com/nocaffeine/ssgclone/product/presentation/ViewHistoryController.java
src/main/java/com/nocaffeine/ssgclone/product/vo/response/product/ProductSearchPageListResponseVo.java

[REFACTOR] 브랜드 및 검색 조회 페이징

---

src/main/java/com/nocaffeine/ssgclone/common/exception/BaseResponseStatus.java
src/main/java/com/nocaffeine/ssgclone/order/application/OrderServiceImp.java
src/main/java/com/nocaffeine/ssgclone/product/domain/Total.java
src/main/java/com/nocaffeine/ssgclone/product/infrastructure/TotalRepository.java
src/main/java/com/nocaffeine/ssgclone/review/application/ReviewServiceImpl.java

[REFACTOR] 리뷰 집계 구현

---

src/main/java/com/nocaffeine/ssgclone/product/application/TotalService.java
src/main/java/com/nocaffeine/ssgclone/product/application/TotalServiceImpl.java
src/main/java/com/nocaffeine/ssgclone/product/dto/response/total/ProductTotalResponseDto.java
src/main/java/com/nocaffeine/ssgclone/product/infrastructure/TotalRepository.java
src/main/java/com/nocaffeine/ssgclone/product/presentation/TotalController.java
src/main/java/com/nocaffeine/ssgclone/product/vo/response/total/ProductTotalResponseVo.java

[REFACOT] 상품 집계 조회 

---

src/main/java/com/nocaffeine/ssgclone/common/exception/BaseResponseStatus.java
src/main/java/com/nocaffeine/ssgclone/common/exception/ExceptionAdvice.java
src/main/java/com/nocaffeine/ssgclone/common/security/JwtAuthenticationFilter.java
src/main/java/com/nocaffeine/ssgclone/common/security/JwtTokenProvider.java
src/main/java/com/nocaffeine/ssgclone/member/application/AuthService.java
src/main/java/com/nocaffeine/ssgclone/member/application/AuthServiceImpl.java
src/main/java/com/nocaffeine/ssgclone/member/presentation/AuthController.java

- 로그아웃 구현 
- 토큰 검증 또는 토큰이 없을 시 예외처리

[FEAT] 로그아웃 및 JWT 예외처리

---

src/main/java/com/nocaffeine/ssgclone/order/application/OrderService.java
src/main/java/com/nocaffeine/ssgclone/order/application/OrderServiceImp.java
src/main/java/com/nocaffeine/ssgclone/order/domain/Orders.java
src/main/java/com/nocaffeine/ssgclone/order/dto/response/OrderStatusResponseDto.java
src/main/java/com/nocaffeine/ssgclone/order/infrastructure/OrderRepository.java
src/main/java/com/nocaffeine/ssgclone/order/presentation/OrderController.java
src/main/java/com/nocaffeine/ssgclone/order/vo/response/OrderStatusResponseVo.java
src/main/java/com/nocaffeine/ssgclone/product/infrastructure/ProductImageRepository.java

[FIX] 주문 오류 해결

---

src/main/java/com/nocaffeine/ssgclone/product/presentation/ProductCategoryListController.java
src/main/java/com/nocaffeine/ssgclone/product/vo/response/product/CategoryProductPageListResponseVo.java
src/main/java/com/nocaffeine/ssgclone/specialprice/application/SpecialPriceService.java
src/main/java/com/nocaffeine/ssgclone/specialprice/application/SpecialPriceServiceImp.java
src/main/java/com/nocaffeine/ssgclone/specialprice/dto/response/SpecialPriceProductIdResponseDto.java
src/main/java/com/nocaffeine/ssgclone/specialprice/dto/response/SpecialPriceProductPageListResponseDto.java
src/main/java/com/nocaffeine/ssgclone/specialprice/presentation/SpecialPriceController.java
src/main/java/com/nocaffeine/ssgclone/specialprice/vo/response/SpecialPriceProductIPageListResponseVo.java

[REFACTOR] 특가별 상품 id 랜덤 페이징 조회 추가

---

src/main/java/com/nocaffeine/ssgclone/order/application/OrderService.java
src/main/java/com/nocaffeine/ssgclone/order/application/OrderServiceImp.java
src/main/java/com/nocaffeine/ssgclone/order/dto/response/OrderNameAndOrderIdResponseDto.java
src/main/java/com/nocaffeine/ssgclone/order/presentation/OrderController.java
src/main/java/com/nocaffeine/ssgclone/order/vo/response/OrderNameAndOrderIdResponseVo.java

[REFACTOR]  return orderId and orderNumber

---

src/main/java/com/nocaffeine/ssgclone/order/application/OrderServiceImp.java
src/main/java/com/nocaffeine/ssgclone/order/dto/response/OrderInfoAndProductListResponseDto.java
src/main/java/com/nocaffeine/ssgclone/order/dto/response/OrderProductListResponseDto.java
src/main/java/com/nocaffeine/ssgclone/order/vo/response/OrderInfoAndProductListResponseVo.java
src/main/java/com/nocaffeine/ssgclone/order/vo/response/OrderProductListResponseVo.java

[REFACTOR] Feature/order product

---

src/main/java/com/nocaffeine/ssgclone/product/presentation/ProductController.java

[REFACTOR] 전체 상품 조회 오름차순 변경

---

src/main/java/com/nocaffeine/ssgclone/common/exception/BaseResponseStatus.java
src/main/java/com/nocaffeine/ssgclone/product/application/ProductServiceImpl.java
src/main/java/com/nocaffeine/ssgclone/product/infrastructure/ProductCategoryListRepository.java

[REFACTOR] 상품 별 카테고리 조회 메서드 수정

[REFACTOR] 상품 별 카테고리 조회 메서드 수정
